commitizen:
  bump_message: "release $current_version \u2192 $new_version [skip ci]"
  changelog_incremental: true
  name: cz_conventional_commits
  tag_format: v$version
  version: 0.2.18
  version_files:
  - .version