name: npm test

on:
  push:
    branches-ignore:
      - version
  pull_request:
    branches-ignore:
      - version

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*', 'latest']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
